Organization blog posts
VNOI-Admin/OJ pull request #161
Opened 2021-09-05 10:05 UTC by hung3a8

Organization admins with "edit_organization_post" permission can create organization posts that only display inside organization views.
Preview:
![image](https://user-images.githubusercontent.com/52038546/132122920-9830605a-3e3f-447b-af8f-37d18df7cb23.png)
![image](https://user-images.githubusercontent.com/52038546/132122965-7ddfb588-7f32-4328-9684-675e3ce08fa1.png)
![image](https://user-images.githubusercontent.com/52038546/132122977-b8456cdd-f719-4b95-95b3-92e676be9793.png)

2021-09-05 11:37 UTC, leduythuccs requested changes

2021-09-05 11:37 UTC, leduythuccs commented on judge/migrations/0154_blog_post_org.py
> +            field=models.BooleanField(default=False, help_text='Display this blog post at the homepage.', verbose_name='global post'),
The `default=False` make all old blog became hidden to users, so try to run a python script here.

2021-09-05 12:04 UTC, leduythuccs requested changes

2021-09-05 12:04 UTC, leduythuccs commented on templates/blog/personal-list.html
> +        .open-tickets .author {
remove all unused css

2021-09-05 12:04 UTC, leduythuccs commented on templates/blog/personal-list.html
> +        $(document).ready(function () {
I think this js is only used on the homepage, so, please remove it.

2021-09-07 08:01 UTC, hieplpvip approved these changes
Looks good to me

2021-09-07 11:38 UTC, leduythuccs approved these changes
LGTM

2021-09-07 11:38 UTC, merged