Create a notification (Backend only)
VNOI-Admin/OJ pull request #169
Opened 2021-09-08 13:52 UTC by vando2108

2021-09-08 14:02 UTC, leduythuccs requested changes

2021-09-08 14:02 UTC, leduythuccs commented on judge/views/contests.py
> +        return kwargs
this method is useless in this view.

2021-09-08 14:02 UTC, leduythuccs commented on judge/views/problem.py
> +        problem.allowed_languages.set(Language.objects.all())
remove

2021-09-08 14:04 UTC, vando2108 commented on judge/forms.py
> +           'description',
I reuse this Form for create a notification

2021-09-08 14:05 UTC, vando2108 commented on judge/views/contests.py
> +        return kwargs
my bad :< I was remove this

2021-09-08 14:08 UTC, leduythuccs commented on judge/forms.py
> +           'description',
I saw the `CreateNotificationCustomForm`, so why this you use this?

2021-09-09 11:49 UTC, leduythuccs commented
Close due to #171

2021-09-09 11:49 UTC, closed without merging