Allow creating private organizations
VNOI-Admin/OJ pull request #182
Opened 2021-09-20 07:49 UTC by hieplpvip

2021-09-20 08:24 UTC, leduythuccs requested changes

2021-09-20 08:24 UTC, leduythuccs commented on judge/models/profile.py
> +            ('create_private_organization', _('Create private organizations')),
Why do you need this perm? I think the default `add_organization` is enough.

2021-09-20 08:25 UTC, leduythuccs commented on judge/forms.py
> +        if not user.has_perm('judge.change_open_organization'):
`if user and not user.has_perm...`

2021-09-21 01:37 UTC, leduythuccs approved these changes
LGTM

2021-09-21 01:37 UTC, merged

2022-10-02 08:46 UTC, phanvchung commented
hợp nhất cam kết [ad0a13b](https://github.com/VNOI-Admin/OJ/commit/ad0a13b71658403fe33e577179d58ac2ad4b4857) vào bậc thầy