Download contest submission source code
VNOI-Admin/OJ pull request #226
Opened 2022-01-03 11:38 UTC by hung3a8

# Description

Type of change: New feature :rocket:

## What

Users can now download all source code of a contest they have access to.
This feature is fast-coded, as it might be extended into exporting an entire contest in the future.

## Why

This is a feature request from our community.

# How Has This Been Tested?

- [x] Test locally
- [x] Test with file-only languages

# Checklist

- [x] I have explained the purpose of this PR.
- [x] I have performed a self-review of my own code

2022-01-03 12:22 UTC, leduythuccs requested changes
nice works, small fixs required

2022-01-03 12:22 UTC, leduythuccs commented on judge/views/contests.py
> +            submissions = user.submissions.order_by('-id') \
`order_by('-points')`

2022-01-03 12:22 UTC, leduythuccs commented on judge/views/contests.py
> +                        filename = os.path.basename(source)
The file_only url is structured as: `/submission_file/<contest_id>/<user_id>/<file_name>.<ext>`, so using os.path.basename will only get you the `<file_name>.<ext>` part (example: https://oj.vnoi.info/src/611645)

2022-01-03 12:22 UTC, leduythuccs commented on judge/views/contests.py
> +                        pass
add comment: Don't store submission history for file_only languages

2022-01-03 12:22 UTC, leduythuccs commented on judge/views/contests.py
> +                    problems.add(problem)
```python
if problem not in problems: 
    # save the submission has the highest points
    problems.add(problem)
```

2022-01-03 12:22 UTC, leduythuccs commented on judge/views/contests.py
> +        output_dir = tempfile.mktemp(suffix='.zip')
More comments about the main logic of the function (which submission will be stored, how the folder will be structured, ...)

2022-01-18 10:20 UTC, hieplpvip commented
Will update the documentation after this PR is merged.

2022-01-22 14:27 UTC, leduythuccs approved these changes
LGTM

2022-01-22 14:28 UTC, merged