Blog votes
VNOI-Admin/OJ pull request #241
Opened 2022-04-10 04:13 UTC by hung3a8

# Description

Type of change: bug fix, New feature

## What

Users can now vote for personal and global blogs. Organization blogs are excluded.
Hotfix: force `bleach` version to `4.1.0`.

# How Has This Been Tested?

- [x] Local test

# Checklist

- [x] I have explained the purpose of this PR.
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

By submitting this pull request, I confirm that my contribution is made under the terms of the AGPL-3.0 License.

2022-04-10 05:30 UTC, leduythuccs requested changes
seem gud, required some changes

2022-04-10 05:30 UTC, leduythuccs commented on judge/views/blog.py
> +    print('lmao')
remove

2022-04-10 05:30 UTC, leduythuccs commented on requirements.txt
> +bleach>=4.1.0,<5.0.0
move this change to master.

2022-04-20 09:54 UTC, hieplpvip reviewed
LGTM

2022-04-21 12:38 UTC, leduythuccs approved these changes
LGTM

2022-04-21 12:38 UTC, merged