Contribution
VNOI-Admin/OJ pull request #52
Opened 2021-05-02 08:18 UTC by leduythuccs

TODO:
- I am too lazy to type it right now

2021-05-04 08:03 UTC, natsukagami requested changes

2021-05-04 08:03 UTC, natsukagami commented on judge/models/profile.py
> +        self.contribution_points += sum([x.is_contributive for x in tickets]) * ticket_step
```suggestion
        self.contribution_points = sum(x.score for x in comments) * cp_reduction
        self.contribution_points += sum(x.is_contributive for x in tickets) * ticket_step
```

2021-05-05 07:51 UTC, natsukagami approved these changes

2021-05-05 07:51 UTC, natsukagami commented on judge/models/profile.py
> +        self.contribution_points += count_good_tickets * settings.VNOJ_CP_TICKET
mình nghĩ nên gộp cái này thành 1 line cho nó dễ hiểu

2021-05-05 08:15 UTC, leduythuccs reviewed
<(") ok merge time

2021-05-05 08:15 UTC, merged