Add organization performance points
VNOI-Admin/OJ pull request #54
Opened 2021-05-02 15:34 UTC by leduythuccs

The function to calculate organization performance points is mostly the same as the point system. You can easily change it in the setting file by replacing `VNOJ_ORG_PP_STEP` and `VNOJ_ORG_PP_ENTRIES`

![image](https://user-images.githubusercontent.com/23715841/116818532-0dce4c80-ab96-11eb-8b96-45257ba976e8.png)

2021-05-02 15:44 UTC, natsukagami requested changes

2021-05-02 15:44 UTC, natsukagami commented on judge/admin/organization.py
> +                                             '%d organization have scores recalculated.',
```suggestion
                                             '%d organizations have scores recalculated.',
```

2021-05-02 15:44 UTC, natsukagami commented on judge/admin/organization.py
> +        self.message_user(request, ungettext('%d organization have scores recalculated.',
```suggestion
        self.message_user(request, ungettext('%d organization has scores recalculated.',
```

2021-05-02 15:44 UTC, natsukagami commented on judge/migrations/0127_add_organization_performance_points.py
> +        ('judge', '0126_allow_blank_desscription'),
cái `desscription` typo có intentional không thế

2021-05-02 15:44 UTC, natsukagami commented on judge/models/profile.py
> +        pp = sum(map(mul, settings.VNOJ_ORG_PP_TABLE[:entries], data[:entries]))
```suggestion
        pp = sum(ratio * pp for ratio, pp in zip(settings.VNOJ_ORG_PP_TABLE, data))
```

2021-05-02 15:44 UTC, natsukagami commented on judge/models/profile.py
> +        if self.performance_points != pp:
cái này là float comparision đấy, đổi thành abs(a - b) < eps đi nếu ko gần như ko baoh cái này là true đâu

2021-05-02 15:46 UTC, leduythuccs commented on judge/migrations/0127_add_organization_performance_points.py
> +        ('judge', '0126_allow_blank_desscription'),
oh cái này có, nhưng mà thế thì hết đổi đc r :v

2021-05-02 15:47 UTC, leduythuccs commented on judge/admin/organization.py
> +                                             '%d organization have scores recalculated.',
Lmao em lag :'( copy xuống xong quên đổi luôn

2021-05-02 17:05 UTC, natsukagami commented on judge/models/profile.py
> +        if self.performance_points != pp:
ủa sao lại resolve cái này :C

2021-05-03 05:36 UTC, leduythuccs commented on judge/models/profile.py
> +        if self.performance_points != pp:
ủa hôm qua em không thấy cái này :v

2021-05-03 13:10 UTC, ngkan approved these changes

2021-05-04 08:06 UTC, natsukagami requested changes

2021-05-04 08:06 UTC, natsukagami commented on judge/models/profile.py
> +        pp = sum([x * y for x, y in zip(table, data)]) + bonus_function(extradata)
```suggestion
        pp = sum(x * y for x, y in zip(table, data)) + bonus_function(extradata)
```

2021-05-04 14:02 UTC, natsukagami approved these changes
![](https://cdn.discordapp.com/emojis/725151219986858074.png?v=1)

2021-05-04 14:04 UTC, merged